import assert from 'node:assert/strict';
import test from 'node:test';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';
import { skillFrontmatter } from '../helpers/skill-metadata.ts';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../../..');
const distribution = join(root, 'packages/claude-plugin');
const authoring = join(root, 'packages/codex-plugin');
const sourceMap = JSON.parse(
  readFileSync(join(root, 'packages/shared-agent-knowledge/source-map.json'), 'utf8'),
) as {
  hostAdaptations: {
    codex: { adaptedDomainSkills: string[]; adaptedCommands: string[]; commandSkills: string[] };
  };
};
const contract = sourceMap.hostAdaptations.codex;

function directories(path: string): string[] {
  return readdirSync(path, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

test('GH-575 generated Codex skill inventory is exactly 28 with migration disabled', () => {
  assert.equal(contract.adaptedDomainSkills.length, 11);
  assert.equal(contract.adaptedCommands.length, 17);
  assert.deepEqual(contract.commandSkills, contract.adaptedCommands);
  const expected = [...contract.adaptedDomainSkills, ...contract.commandSkills].sort();
  assert.equal(new Set(expected).size, 28);
  assert.deepEqual(directories(join(distribution, 'codex-skills')), expected);
  assert.deepEqual(
    directories(join(authoring, 'skills')),
    [...contract.adaptedDomainSkills].sort(),
  );
  for (const manifestPath of [
    join(distribution, '.codex-plugin/plugin.json'),
    join(authoring, '.codex-plugin/plugin.json'),
  ]) {
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as {
      skills?: unknown;
      commands?: unknown;
      mcpServers?: unknown;
      hooks?: unknown;
    };
    assert.equal(manifest.skills, './codex-skills/');
    assert.deepEqual(manifest.commands, []);
    assert.equal(manifest.mcpServers, './codex.mcp.json');
    assert.deepEqual(
      manifest.hooks,
      { hooks: {} },
      'inline empty hooks keep Claude hooks/ out of Codex',
    );
  }
  assert.equal(existsSync(join(distribution, '.codex-plugin/migrated-command-skills')), false);
  assert.equal(
    existsSync(join(distribution, '.mcp.json')),
    false,
    'Claude must not auto-discover the Codex bootstrap',
  );
});

test('GH-575 generated adapters declare explicit-only metadata and package-local links', () => {
  for (const name of contract.commandSkills) {
    const skill = readFileSync(join(distribution, 'codex-skills', name, 'SKILL.md'), 'utf8');
    const metadata = parse(
      readFileSync(join(distribution, 'codex-skills', name, 'agents/openai.yaml'), 'utf8'),
    );
    const frontmatter = skillFrontmatter(skill);
    assert.equal(frontmatter.name, name);
    assert.equal(typeof frontmatter.description, 'string');
    assert.ok(frontmatter.description);
    assert.match(skill, /GENERATED by scripts\/build-host-runtimes\.ts/);
    assert.match(skill, new RegExp(`\\$rn-dev-agent:${name}`));
    assert.match(skill, new RegExp(`\\.\\./\\.\\./codex-commands/${name}\\.md`));
    assert.equal(existsSync(join(distribution, 'codex-commands', `${name}.md`)), true, name);
    assert.equal(metadata.policy.allow_implicit_invocation, false);
    assert.match(metadata.interface.default_prompt, new RegExp(`\\$rn-dev-agent:${name}`));
  }
});

test('GH-575 packaged build workflows match their authoring sources', () => {
  assert.equal(
    readFileSync(join(distribution, 'codex-commands/build-and-test.md'), 'utf8'),
    readFileSync(join(authoring, 'commands/build-and-test.md'), 'utf8'),
  );
  assert.equal(
    readFileSync(join(distribution, 'commands/build-and-test.md'), 'utf8'),
    readFileSync(join(root, 'packages/shared-agent-knowledge/commands/build-and-test.md'), 'utf8'),
  );
});

test('GH-575 installed helper/template dependencies are package-local', () => {
  for (const path of [
    'AGENTS-MD-TEMPLATE.md',
    'bin/cdp-supervisor.js',
    'bin/plugin-health.js',
    'bin/package.json',
    'codex.mcp.json',
    'codex-templates/rn-agent/.scaffold-version',
    'scripts/collect-feedback.sh',
    'scripts/eas_resolve_artifact.sh',
    'scripts/expo_ensure_running.sh',
    'scripts/check-vercel-rules.mjs',
    'scripts/snapshot_state.sh',
    'rn-dev-agent-core/dist/learned-actions.js',
  ]) {
    assert.equal(existsSync(join(distribution, path)), true, path);
  }
  for (const path of [
    'rn-dev-agent-core',
    'scripts',
    'runner-manifest.json',
    'bin/plugin-health.js',
    'AGENTS-MD-TEMPLATE.md',
  ]) {
    assert.equal(existsSync(join(authoring, path)), false, `authoring tree must not ship ${path}`);
  }
});
