import assert from 'node:assert/strict';
import test from 'node:test';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../../..');
const codex = join(root, 'packages/codex-plugin');
const sourceMap = JSON.parse(
  readFileSync(join(root, 'packages/shared-agent-knowledge/source-map.json'), 'utf8'),
) as {
  hostAdaptations: {
    codex: { adaptedDomainSkills: string[]; adaptedCommands: string[]; commandSkills: string[] };
  };
};
const contract = sourceMap.hostAdaptations.codex;

function directories(path: string): string[] {
  return readdirSync(path, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

test('GH-575 generated Codex skill inventory is exactly 25 with migration disabled', () => {
  assert.equal(contract.adaptedDomainSkills.length, 10);
  assert.equal(contract.adaptedCommands.length, 15);
  assert.deepEqual(contract.commandSkills, contract.adaptedCommands);
  const expected = [...contract.adaptedDomainSkills, ...contract.commandSkills].sort();
  assert.equal(new Set(expected).size, 25);
  assert.deepEqual(directories(join(codex, 'skills')), expected);
  const manifest = JSON.parse(readFileSync(join(codex, '.codex-plugin/plugin.json'), 'utf8')) as {
    commands?: unknown;
  };
  assert.deepEqual(manifest.commands, []);
  assert.equal(existsSync(join(codex, '.codex-plugin/migrated-command-skills')), false);
});

test('GH-575 every command adapter is generated, explicit-only, and package-relative', () => {
  for (const name of contract.commandSkills) {
    const skill = readFileSync(join(codex, 'skills', name, 'SKILL.md'), 'utf8');
    const metadata = readFileSync(join(codex, 'skills', name, 'agents/openai.yaml'), 'utf8');
    assert.equal(skill.startsWith('---\n'), true, `${name} must start with YAML frontmatter`);
    assert.match(skill, /GENERATED by scripts\/build-host-runtimes\.ts/);
    assert.match(skill, new RegExp(`name: ${name}(?:\\n|$)`));
    assert.match(skill, new RegExp(`\\$rn-dev-agent:${name}`));
    assert.match(skill, new RegExp(`\\.\\./\\.\\./commands/${name}\\.md`));
    assert.match(skill, /conceptual \*\*request\*\*/);
    assert.match(metadata, /allow_implicit_invocation:\s*false/);
    assert.match(metadata, new RegExp(`\\$rn-dev-agent:${name}`));
  }
});

test('GH-575 build workflow retains artifact and exact-device ownership through install', () => {
  const workflow = readFileSync(join(codex, 'commands/build-and-test.md'), 'utf8');
  assert.match(workflow, /--device-id "<device-id>"/);
  assert.match(workflow, /eas_resolve_artifact\.sh" "<platform>" "<profile>" "<artifact-dir>"/);
  assert.match(workflow, /trap 'rm -rf -- "\$artifact_dir"' EXIT/);
  assert.match(workflow, /every success\n\s+or failure path/);
});

test('GH-575 Claude build workflow uses package-local helpers and exact device identity', () => {
  const shared = readFileSync(
    join(root, 'packages/shared-agent-knowledge/commands/build-and-test.md'),
    'utf8',
  );
  const claude = readFileSync(
    join(root, 'packages/claude-plugin/commands/build-and-test.md'),
    'utf8',
  );
  assert.equal(claude, shared);
  assert.match(shared, /\$CLAUDE_PLUGIN_ROOT\/scripts\/expo_ensure_running\.sh/);
  assert.match(shared, /--device-id "<device-id>"/);
  assert.match(shared, /trap 'rm -rf -- "\$artifact_dir"' EXIT/);
  assert.doesNotMatch(shared, /\$CLAUDE_PLUGIN_ROOT\/\.\.\/\.\.\/scripts/);
});

test('GH-575 setup appends its managed block only when both sentinels are absent', () => {
  const workflow = readFileSync(join(codex, 'commands/setup.md'), 'utf8');
  assert.match(workflow, /Existing file containing neither marker/);
  assert.doesNotMatch(workflow, /Existing file without the start marker/);
});

test('GH-575 Codex runtime instructions contain no Claude substitution or cache-root fallback', () => {
  const files: string[] = [];
  const walk = (path: string): void => {
    for (const entry of readdirSync(path, { withFileTypes: true })) {
      const child = join(path, entry.name);
      if (entry.isDirectory()) walk(child);
      else if (/\.(?:md|ya?ml)$/.test(entry.name)) files.push(child);
    }
  };
  walk(join(codex, 'commands'));
  walk(join(codex, 'skills'));
  files.push(join(codex, 'src/AGENTS-MD-TEMPLATE.md'));
  const joined = files.map((file) => readFileSync(file, 'utf8')).join('\n');
  for (const forbidden of [
    /\$ARGUMENTS/,
    /\$\{ARGUMENTS/,
    /CLAUDE_PLUGIN_ROOT/,
    /RN_DEV_AGENT_CODEX_PLUGIN_ROOT/,
    /CODEX_PLUGIN_ROOT/,
    /\/rn-dev-agent:/,
    /mcp__plugin_rn-dev-agent_cdp__/,
    /\/plugin (?:install|update)/,
    /find [^\n]*plugins\/cache/,
  ]) {
    assert.doesNotMatch(joined, forbidden);
  }
});

test('GH-575 installed helper/template dependencies are package-local', () => {
  for (const path of [
    'AGENTS-MD-TEMPLATE.md',
    'bin/plugin-health.js',
    'scripts/collect-feedback.sh',
    'scripts/eas_resolve_artifact.sh',
    'scripts/expo_ensure_running.sh',
    'scripts/check-vercel-rules.mjs',
    'scripts/snapshot_state.sh',
    'rn-dev-agent-core/dist/learned-actions.js',
  ]) {
    assert.equal(existsSync(join(codex, path)), true, path);
  }
});
