import assert from 'node:assert/strict';
import test from 'node:test';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../../..');
// packages/claude-plugin is the one directory both marketplaces install; the
// Codex surface lives in its codex-* subtrees. packages/codex-plugin is authoring only.
const distribution = join(root, 'packages/claude-plugin');
const authoring = join(root, 'packages/codex-plugin');
const sourceMap = JSON.parse(
  readFileSync(join(root, 'packages/shared-agent-knowledge/source-map.json'), 'utf8'),
) as {
  hostAdaptations: {
    codex: { adaptedDomainSkills: string[]; adaptedCommands: string[]; commandSkills: string[] };
  };
};
const contract = sourceMap.hostAdaptations.codex;

function directories(path: string): string[] {
  return readdirSync(path, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

test('GH-575 generated Codex skill inventory is exactly 28 with migration disabled', () => {
  assert.equal(contract.adaptedDomainSkills.length, 11);
  assert.equal(contract.adaptedCommands.length, 17);
  assert.deepEqual(contract.commandSkills, contract.adaptedCommands);
  const expected = [...contract.adaptedDomainSkills, ...contract.commandSkills].sort();
  assert.equal(new Set(expected).size, 28);
  assert.deepEqual(directories(join(distribution, 'codex-skills')), expected);
  assert.deepEqual(
    directories(join(authoring, 'skills')),
    [...contract.adaptedDomainSkills].sort(),
  );
  for (const manifestPath of [
    join(distribution, '.codex-plugin/plugin.json'),
    join(authoring, '.codex-plugin/plugin.json'),
  ]) {
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as {
      skills?: unknown;
      commands?: unknown;
      mcpServers?: unknown;
      hooks?: unknown;
    };
    assert.equal(manifest.skills, './codex-skills/');
    assert.deepEqual(manifest.commands, []);
    assert.equal(manifest.mcpServers, './codex.mcp.json');
    assert.deepEqual(
      manifest.hooks,
      { hooks: {} },
      'inline empty hooks keep Claude hooks/ out of Codex',
    );
  }
  assert.equal(existsSync(join(distribution, '.codex-plugin/migrated-command-skills')), false);
  assert.equal(
    existsSync(join(distribution, '.mcp.json')),
    false,
    'Claude must not auto-discover the Codex bootstrap',
  );
});

test('GH-575 every command adapter is generated, explicit-only, and package-relative', () => {
  for (const name of contract.commandSkills) {
    const skill = readFileSync(join(distribution, 'codex-skills', name, 'SKILL.md'), 'utf8');
    const metadata = readFileSync(
      join(distribution, 'codex-skills', name, 'agents/openai.yaml'),
      'utf8',
    );
    assert.equal(skill.startsWith('---\n'), true, `${name} must start with YAML frontmatter`);
    assert.match(skill, /GENERATED by scripts\/build-host-runtimes\.ts/);
    assert.match(skill, new RegExp(`name: ${name}(?:\\n|$)`));
    assert.match(skill, new RegExp(`\\$rn-dev-agent:${name}`));
    assert.match(skill, new RegExp(`\\.\\./\\.\\./codex-commands/${name}\\.md`));
    assert.equal(existsSync(join(distribution, 'codex-commands', `${name}.md`)), true, name);
    assert.match(skill, /conceptual \*\*request\*\*/);
    assert.match(metadata, /allow_implicit_invocation:\s*false/);
    assert.match(metadata, new RegExp(`\\$rn-dev-agent:${name}`));
  }
});

test('GH-575 build workflow retains artifact and exact-device ownership through install', () => {
  const workflow = readFileSync(join(distribution, 'codex-commands/build-and-test.md'), 'utf8');
  assert.equal(workflow, readFileSync(join(authoring, 'commands/build-and-test.md'), 'utf8'));
  assert.match(workflow, /--device-id "<device-id>"/);
  assert.match(workflow, /eas_resolve_artifact\.sh" "<platform>" "<profile>" "<artifact-dir>"/);
  assert.match(workflow, /trap 'rm -rf -- "\$artifact_dir"' EXIT/);
  assert.match(workflow, /every success\n\s+or failure path/);
});

test('GH-575 Claude build workflow uses package-local helpers and exact device identity', () => {
  const shared = readFileSync(
    join(root, 'packages/shared-agent-knowledge/commands/build-and-test.md'),
    'utf8',
  );
  const claude = readFileSync(
    join(root, 'packages/claude-plugin/commands/build-and-test.md'),
    'utf8',
  );
  assert.equal(claude, shared);
  assert.match(shared, /CURSOR_PLUGIN_ROOT/);
  assert.match(shared, /expo_ensure_running\.sh/);
  assert.match(shared, /--device-id "<device-id>"/);
  assert.match(shared, /trap 'rm -rf -- "\$artifact_dir"' EXIT/);
  assert.doesNotMatch(shared, /\$CLAUDE_PLUGIN_ROOT\/\.\.\/\.\.\/scripts/);
});

test('GH-575 setup appends its managed block only when both sentinels are absent', () => {
  const workflow = readFileSync(join(distribution, 'codex-commands/setup.md'), 'utf8');
  assert.match(workflow, /Existing file containing neither marker/);
  assert.doesNotMatch(workflow, /Existing file without the start marker/);
});

test('GH-575 Codex runtime instructions contain no Claude substitution or cache-root fallback', () => {
  const files: string[] = [];
  const walk = (path: string): void => {
    for (const entry of readdirSync(path, { withFileTypes: true })) {
      const child = join(path, entry.name);
      if (entry.isDirectory()) walk(child);
      else if (/\.(?:md|ya?ml)$/.test(entry.name)) files.push(child);
    }
  };
  walk(join(distribution, 'codex-commands'));
  walk(join(distribution, 'codex-skills'));
  walk(join(authoring, 'commands'));
  walk(join(authoring, 'skills'));
  files.push(join(distribution, 'AGENTS-MD-TEMPLATE.md'));
  const joined = files.map((file) => readFileSync(file, 'utf8')).join('\n');
  for (const forbidden of [
    /\$ARGUMENTS/,
    /\$\{ARGUMENTS/,
    /CLAUDE_PLUGIN_ROOT/,
    /RN_DEV_AGENT_CODEX_PLUGIN_ROOT/,
    /CODEX_PLUGIN_ROOT/,
    /\/rn-dev-agent:/,
    /mcp__plugin_rn-dev-agent_cdp__/,
    /\/plugin (?:install|update)/,
    /find [^\n]*plugins\/cache/,
  ]) {
    assert.doesNotMatch(joined, forbidden);
  }
});

test('GH-575 installed helper/template dependencies are package-local', () => {
  for (const path of [
    'AGENTS-MD-TEMPLATE.md',
    'bin/cdp-supervisor.js',
    'bin/plugin-health.js',
    'bin/package.json',
    'codex.mcp.json',
    'codex-templates/rn-agent/.scaffold-version',
    'scripts/collect-feedback.sh',
    'scripts/eas_resolve_artifact.sh',
    'scripts/expo_ensure_running.sh',
    'scripts/check-vercel-rules.mjs',
    'scripts/snapshot_state.sh',
    'rn-dev-agent-core/dist/learned-actions.js',
  ]) {
    assert.equal(existsSync(join(distribution, path)), true, path);
  }
  for (const path of [
    'rn-dev-agent-core',
    'scripts',
    'runner-manifest.json',
    'bin/plugin-health.js',
    'AGENTS-MD-TEMPLATE.md',
  ]) {
    assert.equal(existsSync(join(authoring, path)), false, `authoring tree must not ship ${path}`);
  }
});
