#!/usr/bin/env bash
set -euo pipefail

AGENT_DIR="$HOME/.claude/rn-agent"
CONFIG_FILE="$AGENT_DIR/config.json"

if [[ -d "$AGENT_DIR" ]]; then
  exit 0
fi

mkdir -p "$AGENT_DIR/telemetry" "$AGENT_DIR/candidates"
chmod 700 "$AGENT_DIR" "$AGENT_DIR/telemetry" "$AGENT_DIR/candidates"

cat > "$CONFIG_FILE" << 'CONF'
{
  "experience_engine": true,
  "retention_days": 14,
  "max_telemetry_mb": 250,
  "redact_paths": true,
  "redact_secrets": true,
  "redact_pii": true
}
CONF

cat > "$AGENT_DIR/experience.md" << 'EXP'
# Personal Experience

<!-- Auto-generated by rn-dev-agent Experience Engine -->
<!-- This file captures patterns learned from your development sessions -->
<!-- Edit freely — your changes are preserved across compaction cycles -->

## Failure Patterns

_No patterns captured yet. Run /rn-dev-agent:rn-feature-dev to start learning._

## Recovery Shortcuts

_Recovery patterns will appear here after repeated failures are resolved._

## Project Conventions

_Project-specific conventions will be captured as you work._
EXP

echo "rn-dev-agent Experience Engine initialized at $AGENT_DIR"
echo "  Telemetry and failure patterns will be captured locally."
echo "  All data stays on your machine — no cloud, no telemetry."
echo "  To disable: set \"experience_engine\": false in $CONFIG_FILE"
echo "  To reset: rm -rf $AGENT_DIR"
